# Generated by Django 4.1 on 2022-08-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=15)),
                ("f_nacimiento", models.CharField(max_length=10)),
                ("sexo", models.CharField(max_length=30)),
                ("edad", models.CharField(max_length=30)),
                ("altura", models.FloatField()),
            ],
        ),
    ]
